#!/bin/bash
read INPUT

USERNAME=$(echo "$INPUT" | grep -o '"username":"[^"]*"' | cut -d'"' -f4)

if [ -n "$USERNAME" ]; then
    passwd -l "$USERNAME"
    echo "$(date): Disabled user $USERNAME" >> /var/ossec/logs/disable-linux-user.log
fi

exit 0
